name: merchant_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.3.4

dependencies:
  cloud_firestore: ^5.4.4
  enhance_stepper: ^1.0.1
  firebase_auth: ^5.3.1
  firebase_messaging: ^15.1.3
  firebase_core: ^3.6.0
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/gif/
